// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS1hclyTs9hRocA1yqnIBhlK3vjYlskqs',
    appId: '1:589301216717:web:ef21dbac389bd87e140084',
    messagingSenderId: '589301216717',
    projectId: 'eshop-3e72a',
    authDomain: 'eshop-3e72a.firebaseapp.com',
    storageBucket: 'eshop-3e72a.firebasestorage.app',
    measurementId: 'G-8S0R741FP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXCsGqOP8D-puWcLWfp2iX5Y2h12x4150',
    appId: '1:589301216717:android:e5a778af3f9e1acc140084',
    messagingSenderId: '589301216717',
    projectId: 'eshop-3e72a',
    storageBucket: 'eshop-3e72a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaj2m89sNbDQy3Ae8YyO-0C15OMHPc6Tk',
    appId: '1:589301216717:ios:c9e3a2f9ed061501140084',
    messagingSenderId: '589301216717',
    projectId: 'eshop-3e72a',
    storageBucket: 'eshop-3e72a.firebasestorage.app',
    iosBundleId: 'com.example.semaine6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaj2m89sNbDQy3Ae8YyO-0C15OMHPc6Tk',
    appId: '1:589301216717:ios:c9e3a2f9ed061501140084',
    messagingSenderId: '589301216717',
    projectId: 'eshop-3e72a',
    storageBucket: 'eshop-3e72a.firebasestorage.app',
    iosBundleId: 'com.example.semaine6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS1hclyTs9hRocA1yqnIBhlK3vjYlskqs',
    appId: '1:589301216717:web:ddab725b3b87bd94140084',
    messagingSenderId: '589301216717',
    projectId: 'eshop-3e72a',
    authDomain: 'eshop-3e72a.firebaseapp.com',
    storageBucket: 'eshop-3e72a.firebasestorage.app',
    measurementId: 'G-SGCN4XVCRG',
  );
}
